import turtle

input_number = input('Please enter a two digit number')
num1 = input_number[0]
num2 = input_number[1]

tp=turtle.pos()
if(num1 == '0'):
    turtle.pencolor('red')
    turtle.forward(100)
    turtle.right(90)
    turtle.forward(200)
    turtle.right(90)
    turtle.forward(100)
    turtle.right(90)
    turtle.forward(200)
    turtle.right(90)
elif(num1 == '1'):
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(200)
    turtle.left(90)
    turtle.backward(50)
    turtle.forward(100)
elif(num1 == '2'):
    turtle.pencolor('red')
    turtle.forward(100)
    turtle.right(90)
    turtle.forward(100)
    turtle.right(90)
    turtle.forward(100)
    turtle.left(90)
    turtle.forward(100)
    turtle.left(90)
    turtle.forward(100)
elif(num1 == '3'):
    turtle.forward(100)
    turtle.right(90)
    turtle.forward(200)
    turtle.right(90)
    turtle.forward(100)
    turtle.penup()
    turtle.right(90)
    turtle.forward(100)
    turtle.right(90)
    turtle.pendown()
    turtle.forward(100)
elif(num1 == '4'):
    turtle.pencolor('red')
    turtle.right(90)
    turtle.forward(100)
    turtle.left(90)
    turtle.forward(100)
    turtle.right(90)
    turtle.backward(100)
    turtle.forward(200)
    turtle.left(90)
elif(num1 == '5'):
    turtle.forward(100)
    turtle.backward(100)
    turtle.right(90)
    turtle.forward(100)
    turtle.left(90)
    turtle.forward(100)
    turtle.right(90)
    turtle.forward(100)
    turtle.left(90)
    turtle.backward(100)
elif(num1 == '6'):
    turtle.pencolor('red')
    turtle.forward(100)
    turtle.backward(100)
    turtle.right(90)
    turtle.forward(200)
    turtle.left(90)
    turtle.forward(100)
    turtle.left(90)
    turtle.forward(100)
    turtle.left(90)
    turtle.forward(100)
    turtle.left(180)
elif(num1 == '7'):
    turtle.forward(100)
    turtle.right(90)
    turtle.forward(200)
    turtle.left(90)
elif(num1 == '8'):
    turtle.pencolor('red')
    turtle.forward(100)
    turtle.right(90)
    turtle.forward(200)
    turtle.right(90)
    turtle.forward(100)
    turtle.right(90)
    turtle.forward(100)
    turtle.right(90)
    turtle.forward(100)
    turtle.backward(100)
    turtle.left(90)
    turtle.forward(100)
    turtle.right(90)
elif(num1 == '9'):
    turtle.forward(100)
    turtle.right(90)
    turtle.forward(200)
    turtle.right(90)
    turtle.forward(100)
    turtle.penup()
    turtle.right(90)
    turtle.forward(100)
    turtle.right(90)
    turtle.pendown()
    turtle.forward(100)
    turtle.backward(100)
    turtle.left(90)
    turtle.forward(100)
    turtle.right(90)
    

turtle.penup()
turtle.setpos(tp)
turtle.forward(150)
turtle.pendown()
turtle.pencolor('black') 
if(num2 == '0'):
    turtle.pencolor('red')
    turtle.forward(100)
    turtle.right(90)
    turtle.forward(200)
    turtle.right(90)
    turtle.forward(100)
    turtle.right(90)
    turtle.forward(200)
    turtle.right(90)
elif(num2 == '1'):
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(200)
    turtle.left(90)
    turtle.backward(50)
    turtle.forward(100)
elif(num2 == '2'):
    turtle.pencolor('red')
    turtle.backward(100)
    turtle.forward(100)
    turtle.right(90)
    turtle.forward(100)
    turtle.right(90)
    turtle.forward(100)
    turtle.left(90)
    turtle.forward(100)
    turtle.left(90)
    turtle.forward(100)
elif(num2 == '3'):
    turtle.forward(100)
    turtle.right(90)
    turtle.forward(200)
    turtle.right(90)
    turtle.forward(100)
    turtle.penup()
    turtle.right(90)
    turtle.forward(100)
    turtle.right(90)
    turtle.pendown()
    turtle.forward(100)
elif(num2 == '4'):
    turtle.pencolor('red')
    turtle.right(90)
    turtle.forward(100)
    turtle.left(90)
    turtle.forward(100)
    turtle.right(90)
    turtle.backward(100)
    turtle.forward(200)
    turtle.left(90)
elif(num2 == '5'):
    turtle.forward(100)
    turtle.backward(100)
    turtle.right(90)
    turtle.forward(100)
    turtle.left(90)
    turtle.forward(100)
    turtle.right(90)
    turtle.forward(100)
    turtle.left(90)
    turtle.backward(100)
elif(num2 == '6'):
    turtle.pencolor('red')
    turtle.forward(100)
    turtle.backward(100)
    turtle.right(90)
    turtle.forward(200)
    turtle.left(90)
    turtle.forward(100)
    turtle.left(90)
    turtle.forward(100)
    turtle.left(90)
    turtle.forward(100)
    turtle.left(180)
elif(num2 == '7'):
    turtle.forward(100)
    turtle.right(90)
    turtle.forward(200)
    turtle.left(90)
elif(num2 == '8'):
    turtle.pencolor('red')
    turtle.forward(100)
    turtle.right(90)
    turtle.forward(200)
    turtle.right(90)
    turtle.forward(100)
    turtle.right(90)
    turtle.forward(100)
    turtle.right(90)
    turtle.forward(100)
    turtle.backward(100)
    turtle.left(90)
    turtle.forward(100)
    turtle.right(90)
elif(num2 == '9'):
    turtle.forward(100)
    turtle.right(90)
    turtle.forward(200)
    turtle.right(90)
    turtle.forward(100)
    turtle.penup()
    turtle.right(90)
    turtle.forward(100)
    turtle.right(90)
    turtle.pendown()
    turtle.forward(100)
    turtle.backward(100)
    turtle.left(90)
    turtle.forward(100)
    turtle.right(90)
